Add dashboard ew2020
TotalCross/totalcross-embedded-samples pull request #4
Opened 2020-09-07 18:17 UTC by flsobral

Adds https://github.com/TotalCross/dashboard-sample to this repo

2020-09-07 18:21 UTC, otavio commented
It'd be nice to squash the commit so it provides a linear and clean commit history.

2020-09-08 17:51 UTC, VaneskaSousa requested changes
Thank you for correcting English in the general README.

My only observation is that the example is using version 6.1.0 and still uses the TotalCross key.

2020-09-08 17:51 UTC, VaneskaSousa commented on dashboard-ew2020/src/main/java/com/totalcross/sample/dashboard/RunDashboardSampleApplication.java
> +        TotalCrossApplication.run(DashboardSample.class, "/scr", "848x480x24", "/r", "5443444B3018A93884C5D622");
You need to delete the totalcross key from the parameters and comments

2020-09-11 21:18 UTC, flsobral commented on dashboard-ew2020/src/main/java/com/totalcross/sample/dashboard/RunDashboardSampleApplication.java
> +        TotalCrossApplication.run(DashboardSample.class, "/scr", "848x480x24", "/r", "5443444B3018A93884C5D622");
done

2020-09-11 22:19 UTC, merged